#%RAML 1.0
title: GLAM tool
version: v0.1
baseUri: http://cassandra.synapta.io/api/{GLAM}
protocols:
  - HTTP
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/category:
  description: Lista delle categorie con nome e numero di file presenti.
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "nodes": [
                  {
                      "id": "Media_contributed_by_the_ETH-Bibliothek",
                      "files": 7565,
                      "group": 1
                  },
                  {
                      "id": "ETH-BIB_Mittelholzer-Spitsbergen_flight_1923",
                      "files": 96,
                      "group": 2
                  },
                  {
                      "id": "ETH-BIB_Mittelholzer-Persia_flight_1924-1925",
                      "files": 246,
                      "group": 2
                  }
                ],
                "edges": [
                  {
                    "target": "Media_contributed_by_the_ETH-Bibliothek",
                    "source": null
                  },
                  {
                    "target": "ETH-BIB_Mittelholzer-Spitsbergen_flight_1923",
                    "source": "Media_contributed_by_the_ETH-Bibliothek"
                  },
                  {
                    "target": "ETH-BIB_Mittelholzer-Persia_flight_1924-1925",
                    "source": "Media_contributed_by_the_ETH-Bibliothek"
                  }
                ]
              }

/file/upload-date:
  description: Numero di file caricati raggruppati per giorno di caricamento.
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              [
                  {
                      "_id": {
                          "year": 2016,
                          "month": 5,
                          "day": 17
                      },
                      "count": 1
                  },
                  {
                      "_id": {
                          "year": 2016,
                          "month": 5,
                          "day": 31
                      },
                      "count": 341
                  }
              ]
