#%RAML 1.0
title: GLAM tool
version: v1
baseUri: /api
protocols:
  - HTTP
  - HTTPS
mediaType: application/json
/glams:
  description: Collection of Glams for the main page.
  get:
    description: Get a list of the Glams in a non-paused status.
    responses: 
      200:
        body:
          application/json:
            example: |
              [
                {
                  "name": "ZU",
                  "fullname": "Canton of Zürich",
                  "category": "Category:Historical images of buildings in the canton of Zürich",
                  "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Herrliberger_Elgg_1740.jpg/640px-Herrliberger_Elgg_1740.jpg"
                }
              ]
/admin:
  description: The APIs for the administrative area.
  /glams:
    description: Collection of Glams for the administrative area.
    get:
      description: Get a list of the Glams available in the system.
      responses: 
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "name": "ZU",
                    "fullname": "Canton of Zürich",
                    "category": "Category:Historical images of buildings in the canton of Zürich",
                    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Herrliberger_Elgg_1740.jpg/640px-Herrliberger_Elgg_1740.jpg",
                    "lastrun": "2019-04-08T20:02:35.328Z",
                    "paused": false
                  }
                ]
    post:
      description: Create a new Glam.
      body: 
        application/json:
          type: |
            {
              "type": "object",
              "$schema": "http://json-schema.org/draft-03/schema",
              "id": "http://jsonschema.net",
              "required": true,
              "properties": {
                "name": {
                  "type": "string",
                  "required": true
                },
                "fullname": {
                  "type": "string",
                  "required": true
                },
                "category": {
                  "type": "string",
                  "required": true
                },
                "image": {
                  "type": "string",
                  "required": true
                },
                "password": {
                  "type": "string",
                  "required": false
                }
              }
            }
          example: |
            {
              "name": "ZU",
              "fullname": "Canton of Zürich",
              "category": "Category:Historical images_of buildings in the canton of Zürich",
              "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Herrliberger_Elgg_1740.jpg/640px-Herrliberger_Elgg_1740.jpg",
              "password": "PASSWORD"
            }
    /{glam}:
      description: Entity representing a Glam in the administrative area.
      get:
        description: Get the Glam with `name = {glam}`.
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "name": "ZU",
                    "fullname": "Canton of Zürich",
                    "category": "Category:Historical images_of buildings in the canton of Zürich",
                    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Herrliberger_Elgg_1740.jpg/640px-Herrliberger_Elgg_1740.jpg",
                    "lastrun": "2019-03-26T13:27:13.809Z",
                    "paused": false
                  }
      put:
        description: Update the Glam with `name = {glam}`. An empty password removes the password.
        body:
          application/json:
            type: |
              {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "id": "http://jsonschema.net",
                "required": true,
                "properties": {
                  "name": {
                    "type": "string",
                    "required": true
                  },
                  "fullname": {
                    "type": "string",
                    "required": false
                  },
                  "category": {
                    "type": "string",
                    "required": false
                  },
                  "image": {
                    "type": "string",
                    "required": false
                  },
                  "password": {
                    "type": "string",
                    "required": false
                  },
                  "paused": {
                    "type": "boolean",
                    "required": false
                  }
                }
              }
            example : |
              {
                "name": "ZU",
                "fullname": "Canton of Zürich",
                "category": "Category:Historical images_of buildings in the canton of Zürich",
                "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Herrliberger_Elgg_1740.jpg/640px-Herrliberger_Elgg_1740.jpg",
                "password": "",
                "paused": false
              }
/{glam}:
  description: Entity representing the Glam with `name = {glam}`.
  get:
    responses: 
      200:
        body:
          application/json:
            example: |
              {
                "fullname": "Canton of Zürich",
                "category": "Category:Historical images of buildings in the canton of Zürich",
                "files": "679"
              }
  /category:
    description: List of the categories with their names and the number of available files.
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "nodes": [
                    {
                        "id": "Media_contributed_by_the_ETH-Bibliothek",
                        "files": 7565,
                        "group": 1
                    },
                    {
                        "id": "ETH-BIB_Mittelholzer-Spitsbergen_flight_1923",
                        "files": 96,
                        "group": 2
                    },
                    {
                        "id": "ETH-BIB_Mittelholzer-Persia_flight_1924-1925",
                        "files": 246,
                        "group": 2
                    }
                  ],
                  "edges": [
                    {
                      "target": "Media_contributed_by_the_ETH-Bibliothek",
                      "source": null
                    },
                    {
                      "target": "ETH-BIB_Mittelholzer-Spitsbergen_flight_1923",
                      "source": "Media_contributed_by_the_ETH-Bibliothek"
                    },
                    {
                      "target": "ETH-BIB_Mittelholzer-Persia_flight_1924-1925",
                      "source": "Media_contributed_by_the_ETH-Bibliothek"
                    }
                  ]
                }
  /file/upload-date:
    description: Number of files grouped by upload date and user.
    get:
      queryParameters:
        start:
          description: The start month.
          type: string
          example: "2015-01"
          required: false
        end:
          description: The end month.
          type: string
          example: "2016-01"
          required: false
        sort:
          description: The sorting criteria between user and total.
          type: string
          example: "total"
          required: false
        page:
          description: The page of the results.
          type: integer
          example: 0
          required: false
        limit:
          description: The number of results per page.
          type: integer
          example: 10
          required: false
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                      "user": "ALH",
                      "total": 1
                      "files": [
                          {
                              "date": "2013-08",
                              "count": 1
                          }
                      ]
                  },
                  {
                      "user": "Abderitestatos",
                      "total": 3
                      "files": [
                          {
                              "date": "2009-01",
                              "count": 1
                          },
                          {
                              "date": "2009-09",
                              "count": 1
                          },
                          {
                              "date": "2011-07",
                              "count": 1
                          }
                      ]
                  }
                ]
  /file/upload-date-all:
    description: Number of files grouped by upload date.
    get:
      queryParameters:
        start:
          description: The start month.
          type: string
          example: "2015-01"
          required: false
        end:
          description: The end month.
          type: string
          example: "2016-01"
          required: false
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "count": 1,
                    "date": "2005-12"
                  },
                  {
                    "count": 1,
                    "date": "2006-01"
                  }
                ]
  /views/sidebar:
    description: List of total, average, and median views per file.
    get:
      queryParameters:
        sort:
          description: The sorting criteria among views, median, and name.
          type: string
          example: "views"
          required: false
        page:
          description: The page of the results.
          type: integer
          example: 0
          required: false
        limit:
          description: The number of results per page.
          type: integer
          example: 100
          required: false
      responses: 
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "img_name": "Destruction_of_icons_in_Zurich_1524.jpg",
                    "tot": 29338,
                    "av": 2095.571,
                    "median": 2242.5
                  },
                  {
                    "img_name": "Zürich_Bullinger.jpg",
                    "tot": 18457,
                    "av": 1318.357,
                    "median": 1360.5
                  }
                ]
  /views/files:
    description: List of views of a file per date.
    get:
      queryParameters:
        file:
          description: The name of the file.
          type: string
          example: "11._Schweizerisches_Landesmuseum_-_Zürich.png"
          required: true
        start:
          description: The start month.
          type: string
          example: "2015-01"
          required: false
        end:
          description: The end month.
          type: string
          example: "2016-01"
          required: false
      responses: 
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "sum": 16,
                    "access_date": "2019-03-24"
                  },
                  {
                    "sum": 22,
                    "access_date": "2019-03-25"
                  }
                ]
  /views/by-date:
    description: List of total views per date.
    get:
      queryParameters:
        start:
          description: The start month.
          type: string
          example: "2015-01"
          required: false
        end:
          description: The end month.
          type: string
          example: "2016-01"
          required: false
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                      "date": "2017-01-01",
                      "views": 9810
                  },
                  {
                      "date": "2017-01-02",
                      "views": 4521
                  }
                ]
  /views/all:
    description: Total number of file views.
    get:
      responses:
        200:
          body:
            application/json:
              example:  |
                {
                  "sum": 9812
                }
  /usage:
    description: List of the pages in which each file is used.
    get:
      queryParameters:
        sort:
          description: The sorting criteria among usage, projects, and name.
          type: string
          example: "usage"
          required: false
        page:
          description: The page of the results.
          type: integer
          example: 0
          required: false
        limit:
          description: The number of results per page.
          type: integer
          example: 10
          required: false
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "image": "11._Schweizerisches_Landesmuseum_-_Zürich.png",
                    "usage": 2,
                    "projects": 2,
                    "pages": [
                      {
                        "wiki": "dewiki",
                        "title": "Rathaus_St._Johann"
                      },
                      {
                        "wiki": "frwiki",
                        "title": "Haute_École_d'art_de_Zurich"
                      }
                    ]
                  }
                ]
    /top:
      description: List of the number of files used per wiki, limited to 10 results.
      get:
        responses: 
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "tipo": "dewiki",
                      "n": "483"
                    },
                    {
                      "tipo": "enwiki",
                      "n": "102"
                    }
                  ]
    /stat:
      description: Entity with some statistics about the files used.
      get:
        responses: 
          200:
            body:
              application/json:
               example: |
                {
                  "totalUsage": "783",
                  "totalImagesUsed": "351",
                  "totalProjects": "47",
                  "totalPages": "783"
                }
    /sidebar:
      description: List of the number of pages and wikis per file used, limited to 1000 results.
      get:
        responses: 
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "gil_to": "Destruction_of_icons_in_Zurich_1524.jpg",
                      "wiki": "15",
                      "u": "25"
                    },
                    {
                      "gil_to": "Spelterini_Zürich_City.jpg",
                      "wiki": "6",
                      "u": "21"
                    }
                  ]