#%RAML 1.0
title: GLAM tool
version: v1
baseUri: http://cassandra.synapta.io/api{version}/{GLAM}
protocols:
  - HTTP
  - HTTPS
mediaType: application/json
/category:
  displayName: Category tree
  description: Lista delle categorie con nome e numero di file presenti.
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "nodes": [
                  {
                      "id": "Media_contributed_by_the_ETH-Bibliothek",
                      "files": 7565,
                      "group": 1
                  },
                  {
                      "id": "ETH-BIB_Mittelholzer-Spitsbergen_flight_1923",
                      "files": 96,
                      "group": 2
                  },
                  {
                      "id": "ETH-BIB_Mittelholzer-Persia_flight_1924-1925",
                      "files": 246,
                      "group": 2
                  }
                ],
                "edges": [
                  {
                    "target": "Media_contributed_by_the_ETH-Bibliothek",
                    "source": null
                  },
                  {
                    "target": "ETH-BIB_Mittelholzer-Spitsbergen_flight_1923",
                    "source": "Media_contributed_by_the_ETH-Bibliothek"
                  },
                  {
                    "target": "ETH-BIB_Mittelholzer-Persia_flight_1924-1925",
                    "source": "Media_contributed_by_the_ETH-Bibliothek"
                  }
                ]
              }

/file/upload-date:
  displayName: Uploads
  description: Numero di file caricati raggruppati per giorno di caricamento.
  get:
    queryParameters:
      start:
        displayName: Start month
        type: string
        description: Filtro per mese di inizio
        example: "2015/01"
        required: false
      end:
        displayName: End month
        type: string
        description: Filtro per mese di fine
        example: "2016/01"
        required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "timestamp": "2017/01/16",
                  "users": [
                      {
                          "user": "ALH",
                          "files": [
                              {
                                  "date": "2013/08",
                                  "count": 1
                              }
                          ]
                      },
                      {
                          "user": "Abderitestatos",
                          "files": [
                              {
                                  "date": "2009/01",
                                  "count": 1
                              },
                              {
                                  "date": "2009/09",
                                  "count": 1
                              },
                              {
                                  "date": "2011/07",
                                  "count": 1
                              }
                           ]
                      }
                  ]
              }
/views/by-date:
  displayName: Views by date
  description: Lista del numero complessivo di visualizzazioni dei file per giorno.
  get:
    responses:
      200:
        body:
          application/json:
            example:  |
              {
                [
                  {
                      "date":"2017-01-01",
                      "views":9810
                  },
                  {
                      "date":"2017-01-02",
                      "views":4521
                  }
                ]
              }
/views/all:
  displayName: All views
  description: Numero complessivo di visualizzazioni dei file dall'inizio del tracking (??/??/????).
  get:
    responses:
      200:
        body:
          application/json:
            example:  |
              {
                  "sum":9812
              }
/usage:
  displayName: Pages using files
  description: Lista delle pagine in cui viene utilizzato ogni file.
  get:
    responses:
      200:
        body:
          application/json:
            example:  |
              {
                [
                  {
                      "image":"photoX.png",
                      "pages":
                      [
                          {
                              "wiki":"enwiki",
                              "title":"Page using the photoX"
                          },
                          {
                              "wiki":"itwiki",
                              "title":"Another page using the photoX"
                          }
                      ]
                  },
                  {
                      "image":"photoY.png",
                      "pages":
                      [
                          {
                              "wiki":"dewiki",
                              "title":"Page using the photoY"
                          },
                          {
                              "wiki":"itwiki",
                              "title":"Another page using the photoX"
                          }
                      ]
                  }
                ]
              }
